### ISSUE TITLE
运行直接报错

### ISSUE THREAD

**Issue by shen-lan** [jzlikewei/zhihu-spiders#2]
fetch_all_answers 
ansers+= ret.json()
错误大概定位到这里

**Comment by jzlikewei** [comment]
这个是2年前的知乎爬虫了，我刚刚粗看了下，应该是有些接口变掉了。

**Comment by jzlikewei** [comment]
> fetch_all_answers
> ansers+= ret.json()
> 错误大概定位到这里

fixed
